-- MySQL Script generated by MySQL Workbench
-- qui 08 mar 2018 18:41:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbvendaslaravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbvendaslaravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbvendaslaravel` DEFAULT CHARACTER SET utf8 ;
USE `dbvendaslaravel` ;

-- -----------------------------------------------------
-- Table `dbvendaslaravel`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvendaslaravel`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(256) NULL,
  `cond` TINYINT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbvendaslaravel`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvendaslaravel`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `estoque` INT NOT NULL,
  `descricao` VARCHAR(512) NULL,
  `imagem` VARCHAR(45) NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idarticulo`),
  INDEX `fk_articulo_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_articulo_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbvendaslaravel`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbvendaslaravel`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvendaslaravel`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `tipo_pessoa` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(30) NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbvendaslaravel`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvendaslaravel`.`entrada` (
  `identrada` INT NOT NULL AUTO_INCREMENT,
  `idprovedor` INT NOT NULL,
  `tipo_comprovante` VARCHAR(20) NOT NULL,
  `serie_comprovante` VARCHAR(10) NOT NULL,
  `num_comprovante` VARCHAR(8) NOT NULL,
  `hora_fechamento` DATETIME NOT NULL,
  `imposto` DECIMAL(4,2) NOT NULL,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`identrada`),
  INDEX `fk_entrada_pessoa_idx` (`idprovedor` ASC),
  CONSTRAINT `fk_entrada_pessoa`
    FOREIGN KEY (`idprovedor`)
    REFERENCES `dbvendaslaravel`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbvendaslaravel`.`detalhe_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvendaslaravel`.`detalhe_entrada` (
  `iddetalhe_entrada` INT NOT NULL AUTO_INCREMENT,
  `identrada` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_compra` DECIMAL(11,2) NOT NULL,
  `preco_venda` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`iddetalhe_entrada`),
  INDEX `fk_detalhe_entrada_1_idx` (`identrada` ASC),
  INDEX `fk_detalhe_entrada_articulo_idx` (`idarticulo` ASC),
  CONSTRAINT `fk_detalhe_entrada_1`
    FOREIGN KEY (`identrada`)
    REFERENCES `dbvendaslaravel`.`entrada` (`identrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhe_entrada_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbvendaslaravel`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbvendaslaravel`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvendaslaravel`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `tipo_comprovante` VARCHAR(20) NOT NULL,
  `serie_comprovante` VARCHAR(7) NOT NULL,
  `num_comprovante` VARCHAR(10) NOT NULL,
  `hora_fechamento` DATETIME NOT NULL,
  `imposto` DECIMAL(4,2) NOT NULL,
  `total_venda` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_cliente_idx` (`idcliente` ASC),
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `dbvendaslaravel`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbvendaslaravel`.`detalhe_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvendaslaravel`.`detalhe_venda` (
  `iddetalhe_venda` INT NOT NULL AUTO_INCREMENT,
  `idvenda` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_venda` DECIMAL(11,2) NOT NULL,
  `desconto` DECIMAL(11,2) NULL,
  PRIMARY KEY (`iddetalhe_venda`),
  INDEX `fk_detalhe_venda_articulo_idx` (`idarticulo` ASC),
  INDEX `fk_detalhe_venda__idx` (`idvenda` ASC),
  CONSTRAINT `fk_detalhe_venda_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbvendaslaravel`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhe_venda_`
    FOREIGN KEY (`idvenda`)
    REFERENCES `dbvendaslaravel`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
